USE [master]
GO

/****** Object:  Database [δύνΰυσι]    Script Date: 14.04.2023 1:57:57 ******/
CREATE DATABASE [δύνΰυσι]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'δύνΰυσι', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\δύνΰυσι.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'δύνΰυσι_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\δύνΰυσι_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [δύνΰυσι].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [δύνΰυσι] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [δύνΰυσι] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [δύνΰυσι] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [δύνΰυσι] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [δύνΰυσι] SET ARITHABORT OFF 
GO

ALTER DATABASE [δύνΰυσι] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [δύνΰυσι] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [δύνΰυσι] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [δύνΰυσι] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [δύνΰυσι] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [δύνΰυσι] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [δύνΰυσι] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [δύνΰυσι] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [δύνΰυσι] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [δύνΰυσι] SET  DISABLE_BROKER 
GO

ALTER DATABASE [δύνΰυσι] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [δύνΰυσι] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [δύνΰυσι] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [δύνΰυσι] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [δύνΰυσι] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [δύνΰυσι] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [δύνΰυσι] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [δύνΰυσι] SET RECOVERY FULL 
GO

ALTER DATABASE [δύνΰυσι] SET  MULTI_USER 
GO

ALTER DATABASE [δύνΰυσι] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [δύνΰυσι] SET DB_CHAINING OFF 
GO

ALTER DATABASE [δύνΰυσι] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [δύνΰυσι] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [δύνΰυσι] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [δύνΰυσι] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [δύνΰυσι] SET QUERY_STORE = OFF
GO

ALTER DATABASE [δύνΰυσι] SET  READ_WRITE 
GO


